name: Test code quality
on:
  push
env:
  API_URL: ${{ secrets.API_URL }}
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: ['css-lint', 'js-lint']
    steps:
    - name: Setup Node 12.x
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
    - name: Upload repository
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Start ${{ matrix.script }}
      run: npm run ${{ matrix.script }}
